spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: pass1234
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false

pl:
  fc:
    invoicing:
      db: jpa